---
- hosts: all
  connection: ssh
  tasks:
    - name: Delete App
      command: oc delete project easytravel
      become: true
      
    - name: Wait for 20 seconds
      pause:
        seconds: 35
   
    - name: Get Pods
      command: oc get pods
      become: true
