---
- name: Get pods in OpenShift cluster
  hosts: all
  connection: ssh 
  tasks:
  
   - name: Login to OpenShift cluster
     command: oc login -u admin -p elelUx1T7XajD9EY https://api.cluster-qhbht.qhbht.sandbox39.opentlc.com:6443
   
   - name: Get pods
     command: oc get pods
     register: pods_output

   - name: Display pods output
     debug:
       var: pods_output.stdout_lines

   - name: Notify Slack channel
     slack:
       token: "{{ T0508SWKB2N/B04V8C4P6A3/fr3b7rtyxJrZgjuRqQ1UCT1d }}"
       channel: "#devops"
       text: "Deployment complete!"
