---
- name: Get pods in OpenShift cluster
  hosts: all
  connection: ssh 
  tasks:
   
    - name: Get pods
      command: oc get pods
      register: pods_output

    - name: Display pods output
      debug:
        var: pods_output.stdout_lines
