---
- name: Clone GitHub repository
  hosts: all
  gather_facts: false

  vars:
    github_username: "pmedilall"
    github_repository: "lab-insecurebank"

  tasks:
    - name: Clone the GitHub repository
      become: false
      shell: git clone https://github.com/{{ github_username }}/{{ github_repository }}.git
      
    - name: Wait for 35 seconds
      pause:
       seconds: 35      

    - name: Notify Slack channel
      slack:
        token: "T0508SWKB2N/B04V8C4P6A3/fr3b7rtyxJrZgjuRqQ1UCT1d"
        channel: "#devops"
        msg: "*The repo has been forked where the exploit exsists. Please review and identify fix for the vulnerability! Link to repo - https://source.control.internal/app-insecure*"
