---
- name: Login to OpenShift cluster
  hosts: all
  connection: ssh
  tasks:
    - name: Login to OpenShift cluster
      command: oc login -u admin -p elelUx1T7XajD9EY https://api.cluster-qhbht.qhbht.sandbox39.opentlc.com:6443
    - name: Set environment variable for deployment config
      command: oc set env dc/easytravel-loadgen ET_PROBLEMS=LoginProblems -n travel-apps
