---
- name: Login to OpenShift cluster
  hosts: all
  connection: ssh
  tasks:
    - name: Login to OpenShift cluster
      command: oc login -u admin -p elelUx1T7XajD9EY https://api.cluster-qhbht.qhbht.sandbox39.opentlc.com:6443
    - name: Set environment variable for deployment config
      command: oc set env dc/easytravel-loadgen ET_BACKEND_URL=http://easytravel-www:8080 ET_PROBLEMS=LoginProblems -n easytravel

    - name: Notify Slack channel
       slack:
       token: "T0508SWKB2N/B04V8C4P6A3/fr3b7rtyxJrZgjuRqQ1UCT1d"
       channel: "#devops"
       msg: "*P1 There is suspicious activity occuring on Web System with uncommon Spikes in traffic - Security Response has been notified*!"
