---
- name: Create and Apply Network Policy to Block All Traffic in and out of a Pod
  hosts: localhost
  tasks:
    - name: Create Network Policy Definition
      blockinfile:
        path: network-policy.yaml
        block: |
          apiVersion: networking.k8s.io/v1
          kind: NetworkPolicy
          metadata:
            name: block-all-traffic-policy
          spec:
            podSelector:
              matchLabels:
                app: isolated-pod
            policyTypes:
              - Ingress
              - Egress
            ingress:
              - {}
            egress:
              - {}

