---
- hosts: all
  connection: ssh
  tasks:
    - name: Create EasyTravel deployment
      command: oc create -f easytravel-deployment.yml
      become: true
      delay: 5
      sleep: 5
      
    - name: Create Dynatrace EasyTravel app
      command: oc new-app dynatrace-easytravel2
      become: true
