---
- name: Scale EasyTravel MongoDB deployment Up
  hosts: all
  connection: ssh
  gather_facts: no
  tasks:
  
    - name: Login to OpenShift cluster
      command: oc login -u admin -p uLPBCR7y1RENYE0E https://api.cluster-rldkk.rldkk.sandbox2507.opentlc.com:6443
     
    - name: Scale deployment
      command: oc scale deployment easytravel-mongodb -n easytravel --replicas=1
      
    - name: Wait for 30 seconds
      pause:
        seconds: 30    

    - name: Notify Slack channel
     slack:
      token: "T0508SWKB2N/B04V8C4P6A3/fr3b7rtyxJrZgjuRqQ1UCT1d"
      channel: "#devops"
      msg: "*Processing remediation Workflow. Please wait 5 minutes for the DB to come up*"  
      
