---
- name: Scale EasyTravel MongoDB deployment Up
  hosts: all
  connection: ssh
  gather_facts: no
  tasks:
  
    - name: Login to OpenShift cluster
      command: oc login -u admin -p uLPBCR7y1RENYE0E https://api.cluster-rldkk.rldkk.sandbox2507.opentlc.com:6443
     
    - name: Scale deployment
      command: oc scale deployment easytravel-mongodb -n easytravel --replicas=1
