---
- name: Deploy Dynatrace agent on Windows
  hosts: all
  connection: ssh
 

    - name: Run Dynatrace Agent installer
      win_command: powershell.exe -ExecutionPolicy Bypass -File C:\Users\Administrator\Dynatrace-OneAgent-Windows-1.271.135.20230810-115019.exe --set-app-log-content-access=true --set-instrumentation=true --set-instrumentation-timeout=120 --set-host-tags=environment:production
      when: download_result|success

    - name: Check Dynatrace Agent status
      win_shell: Get-Service -Name "OneAgent" -ErrorAction SilentlyContinue
      register: agent_status

    - name: Restart Dynatrace Agent service if not running
      win_service:
        name: "OneAgent"
        state: started
      when: agent_status.rc != 0


    - name: Notify Slack channel
      slack:
       token: "T0508SWKB2N/B04V8C4P6A3/fr3b7rtyxJrZgjuRqQ1UCT1d"
       channel: "#devops"
       msg: "*Successfully deployed Dynatrace Agent to Windows*"
