---
- name: Get pods in OpenShift cluster
  hosts: all
  connection: ssh 
  vars:
    token: "{{ lookup('env', 'T0508SWKB2N/B04V8C4P6A3/fr3b7rtyxJrZgjuRqQ1UCT1d ') }}"  # use environment variable for Slack API token
    channel: "#devops"  # replace with the name of the Slack channel you want to send the message to
    message: "Deployment complete"  # replace with the message you want to send
  
  
  tasks:
  
   - name: Login to OpenShift cluster
     command: oc login -u admin -p elelUx1T7XajD9EY https://api.cluster-qhbht.qhbht.sandbox39.opentlc.com:6443
   
   - name: Get pods
     command: oc get pods
     register: pods_output

   - name: Display pods output
     debug:
       var: pods_output.stdout_lines

   - name: Notify Slack channel
     slack:
       token: "T0508SWKB2N/B04V8C4P6A3/fr3b7rtyxJrZgjuRqQ1UCT1d"
       channel: "#devops"
       msg: "*Workflow: Ansible and Dynatrace Security Event Workflow has been completed*"

